/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ome.jxrlib;

public class FormatError {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FormatError(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FormatError obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JXRJNI.delete_FormatError(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FormatError(String what_arg) {
    this(JXRJNI.new_FormatError(what_arg), true);
  }

  public String what() {
    return JXRJNI.FormatError_what(swigCPtr, this);
  }

}
