/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class GUID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GUID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GUID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JXRJNI.delete_GUID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData1(long value) {
    JXRJNI.GUID_Data1_set(swigCPtr, this, value);
  }

  public long getData1() {
    return JXRJNI.GUID_Data1_get(swigCPtr, this);
  }

  public void setData2(int value) {
    JXRJNI.GUID_Data2_set(swigCPtr, this, value);
  }

  public int getData2() {
    return JXRJNI.GUID_Data2_get(swigCPtr, this);
  }

  public void setData3(int value) {
    JXRJNI.GUID_Data3_set(swigCPtr, this, value);
  }

  public int getData3() {
    return JXRJNI.GUID_Data3_get(swigCPtr, this);
  }

  public void setData4(short[] value) {
    JXRJNI.GUID_Data4_set(swigCPtr, this, value);
  }

  public short[] getData4() {
    return JXRJNI.GUID_Data4_get(swigCPtr, this);
  }

  public GUID() {
    this(JXRJNI.new_GUID(), true);
  }

}
