/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ome.jxrlib;

public class ImageEncoder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImageEncoder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageEncoder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JXRJNI.delete_ImageEncoder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ImageEncoder(Stream encodeStream, String extension) {
    this(JXRJNI.new_ImageEncoder(Stream.getCPtr(encodeStream), encodeStream, extension), true);
  }

  public void initializeWithDecoder(ImageDecoder decoder) throws ome.jxrlib.FormatError {
    JXRJNI.ImageEncoder_initializeWithDecoder(swigCPtr, this, ImageDecoder.getCPtr(decoder), decoder);
  }

  public void writeSource(FormatConverter converter) throws ome.jxrlib.FormatError {
    JXRJNI.ImageEncoder_writeSource(swigCPtr, this, FormatConverter.getCPtr(converter), converter);
  }

  public void close() {
    JXRJNI.ImageEncoder_close(swigCPtr, this);
  }

}
