/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ome.jxrlib;

class CodecFactory {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CodecFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CodecFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JXRJNI.delete_CodecFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ImageDecoder decoderFromFile(java.io.File inputFile) {
    return decoderFromFile(inputFile.getAbsolutePath());
  }
  
  public ImageDecoder decoderFromFile(String inputFile) {
    return new ImageDecoder(JXRJNI.CodecFactory_decoderFromFile(swigCPtr, this, inputFile), true);
  }

  public ImageDecoder decoderFromBytes(byte[] bytes, long len) {
    return new ImageDecoder(JXRJNI.CodecFactory_decoderFromBytes(swigCPtr, this, bytes, len), true);
  }

  public FormatConverter createFormatConverter(ImageDecoder imageDecoder, String extension) {
    return new FormatConverter(JXRJNI.CodecFactory_createFormatConverter(swigCPtr, this, ImageDecoder.getCPtr(imageDecoder), imageDecoder, extension), true);
  }

  public CodecFactory() {
    this(JXRJNI.new_CodecFactory(), true);
  }

}
