/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ome.jxrlib;

class Factory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Factory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Factory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JXRJNI.delete_Factory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Stream createStreamFromFilename(String filename) {
    return new Stream(JXRJNI.Factory_createStreamFromFilename(swigCPtr, this, filename), true);
  }

  public Factory() {
    this(JXRJNI.new_Factory(), true);
  }

}
